<?php
/**
 * Created by PhpStorm.
 * User: HT
 * Date: 2017/11/06
 * Time: 20:30
 */

namespace app\api\controller\v1;


use app\api\controller\Common;
use app\common\lib\Aes;
use app\common\lib\exception\ApiException;
use Symfony\Component\Yaml\Tests\A;


/**
 * 关于token登录，最好的方式是服务端按照自己的算法生成token，发送到客户端，然后客户端按照服务端的解密算法解密得到真正的token，
 * 然后按照客户端自己的算法进行加密，返回给服务端，服务端在按照客户端的解密算法进行解密校验
 * Class AuthBase
 * @package app\api\controller\v1
 */
class AuthBase extends Common
{
    /**
     * 登录用户信息
     * @var null
     */
    public $user = null;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if($this->isLogin()) {
            throw new ApiException('您没有登录', 401);
        }
    }

    /**
     * 判断是否登录
     */
    public function isLogin()
    {
        if(empty($this->headers['access_user_token'])) {
            return false;
        }

        $aes = new Aes();
        $accessToken = $aes->decrypt($this->headers['access_user_token']);
        if(empty($accessToken)) {
            return false;
        }
        if(!preg_match('/||/', $accessToken))
        {
            return false;
        }

        list($token, $id) = explode('||', $accessToken);
        $user = User::get(['token' => $token]);
        if(!$user || $user->status != 1) {
            return false;
        }

//        判断时间是否过期
        if(time() > $user->time_out) {
            return false;
        }
        $this->user = $user;
        return true;
    }
}